In [1]:
import sqlite3

import matplotlib
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Carga de la tabla drivers

drivers = pd.read_csv(
    "../data/drivers.csv",
    sep=",",
    thousands=None,
    decimal=".",
)
drivers.head()

,driverId,name,ssn,location,certified,wage-plan
0,10,George Vetticaden,621011971,244-4532 Nulla Rd.,N,miles
1,11,Jamie Engesser,262112338,366-4125 Ac Street,N,miles
2,12,Paul Coddin,198041975,Ap #622-957 Risus. Street,Y,hours
3,13,Joe Niemiec,139907145,2071 Hendrerit. Ave,Y,hours
4,14,Adis Cesir,820812209,Ap #810-1228 In St.,Y,hours

In [3]:
# Carga de la tabla timesheet
timesheet = pd.read_csv(
    "../data/timesheet.csv",
    sep=",",
    thousands=None,
    decimal=".",
)
timesheet.head()

   driverId  week  hours-logged  miles-logged
0        10     1            70          3300
1        10     2            70          3300
2        10     3            60          2800
3        10     4            70          3100
4        10     5            70          3200

In [4]:
# Conexión a la base de datos SQLite y almacena las tablas

connection = sqlite3.connect("../temp/db.sqlite")

drivers.to_sql("drivers_raw", connection, if_exists="replace", index=False)
timesheet.to_sql("timesheet_raw", connection, if_exists="replace", index=False)

1768

In [5]:
# Crea vistas para las tablas drivers y timesheet

connection.executescript(
    """
    DROP VIEW IF EXISTS drivers;
    DROP VIEW IF EXISTS timesheet;

    CREATE VIEW drivers AS
    SELECT
        driverId AS driver_id,
        name,
        ssn,
        location,
        certified,
        "wage-plan" AS wage_plan
    FROM drivers_raw;

    CREATE VIEW timesheet AS
    SELECT
        driverId AS driver_id,
        week,
        "hours-logged" AS hours_logged,
        "miles-logged" AS miles_logged
    FROM timesheet_raw;
    """
)
connection.commit()